name = "mynth/data-tokens"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "LGPL-3.0"
description = "Cardano minting policy that allows embedding 33 bytes of data into a token"

[repository]
user = "mynth"
project = "data-tokens"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
