name: data-tokens CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-typescript:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci --include dev

      - name: Validate TypeScript
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci --include dev

      - name: Install Aiken
        run: |
          curl -sSfL https://install.aiken-lang.org | bash
          ~/.aiken/bin/aikup
          sudo ln -s ~/.aiken/bin/aiken /usr/local/bin/aiken

      - name: Setup taplo
        run: curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-linux-x86_64.gz | gzip -d - | sudo install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: Lint
        run: npm run lint

  test-aiken:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Install Aiken
        run: |
          curl -sSfL https://install.aiken-lang.org | bash
          ~/.aiken/bin/aikup
          sudo ln -s ~/.aiken/bin/aiken /usr/local/bin/aiken

      - name: Test Aiken
        run: aiken check

  test-typescript:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci --include dev

      - name: Install Aiken
        run: |
          curl -sSfL https://install.aiken-lang.org | bash
          ~/.aiken/bin/aikup
          sudo ln -s ~/.aiken/bin/aiken /usr/local/bin/aiken

      - name: Build plutus.json
        run: aiken build

      - name: Run tests
        run: npm run test
        env:
          BLOCKFROST_API_KEY: ${{ secrets.BLOCKFROST__PREVIEW_API_KEY }}
          BLOCKFROST_PREPROD_KEY: ${{ secrets.BLOCKFROST__PREPROD_API_KEY }}
